[package]
name = "libpvm-harness"
version = "0.1.0"
authors = ["Thomas Bytheway <tb403@cam.ac.uk>"]
edition = "2018"

[dependencies]
libopus = { path = "modules/libpvm-rs" }
kafka = "0.7"
prometheus = "0.4"
clap = "~2.27.0"
ctrlc = { version = "3.0", features = ["termination"] }
log = "0.4"
env_logger = "0.5"
openssl = "0.9"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.*"
toml = "0.4"
maplit = "1.0"
uuid = { version = "0.6", features = ["serde", "v5"] }
avro-rs = { path = "modules/avro-rs" }
lazy_static = "*"