[package]
name = "libpvm-harness"
version = "0.1.0"
authors = ["Thomas Bytheway <tb403@cam.ac.uk>"]

[dependencies]
libopus = { path = "modules/libpvm-rs" }
kafka = "0.7"
prometheus = "0.4"
clap = "~2.27.0"
serde_json = "*"
ctrlc = { version = "3.0", features = ["termination"] }